os: linux
dist: bionic
language: shell

services:
  - docker

env:
  global:
  - NJOBS="2"
  - PACKAGE_NAME="coq-color"
  jobs:
  - COQ_IMAGE="coqorg/coq:8.11"
  - COQ_IMAGE="coqorg/coq:8.12"
  - COQ_IMAGE="coqorg/coq:dev"

install: |
  # Prepare the COQ container
  docker pull ${COQ_IMAGE}
  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${PACKAGE_NAME} -w /home/coq/${PACKAGE_NAME} ${COQ_IMAGE}
  docker exec COQ /bin/bash --login -c "
    # This bash script is double-quoted to interpolate Travis CI env vars:
    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
    set -ex  # -e = exit on failure; -x = trace for debug
    opam update -y
    opam pin add ${PACKAGE_NAME} . --kind=path --no-action -y
    opam config list; opam repo list; opam pin list; opam list
    " install

script:
- echo -e "${ANSI_YELLOW}Building ${PACKAGE_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
- |
  docker exec COQ /bin/bash --login -c "
    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '; set -ex
    sudo chown -R coq:coq /home/coq/${PACKAGE_NAME}
    # First install the dependencies
    opam install ${PACKAGE_NAME} --deps-only -y
    opam list
    # Then install the package itself in verbose mode
    opam install ${PACKAGE_NAME} -v -y
    " script
- echo -en 'travis_fold:end:script\\r'

after_script:
- docker stop COQ  # optional but recommended
